GameStore1/Controllers/CheckoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GameStore1.DB;
using GameStore1.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace GameStore1.Controllers
{
    public class CheckoutController : Controller
    {
        // GET: /<controller>/
        private readonly GameContext _context;

        public CheckoutController(GameContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            //Check if user is logged in. 
            string userSession = Request.Cookies["CartSessionId"];
            Session session = _context.Sessions.Find(userSession);

            //If user is not logged in, redirect to login 
            if (session.Username == null)
            {
                return RedirectToAction("Index", "Login");
            }

            CreateOrder(userSession, session.Username);

            GenerateActivationCode();

            ClearCartSession();

            return RedirectToAction("Index", "MyPurchases");
        }

        public List<Cart> GetCart()
        {
            string CartSessionId = Request.Cookies["CartSessionId"];
            List<Cart> cartitems = _context.Carts.Where(x => x.SessionId == CartSessionId).ToList();
            return cartitems;
        }

        public void CreateOrder(string userSession, string username)
        {
            List<Cart> cartList = GetCart();

            decimal? total = (from cartItems in _context.Carts
                              where cartItems.SessionId == userSession
                              select (int?)cartItems.Quantity * cartItems.Game.Price).Sum();

            Order order = new Order()
            {

                OrderId = userSession,
                Userusername = username,
                Total = (decimal)total,
                OrderDate = DateTime.Now
            };

            _context.Add(order);
            _context.SaveChanges();

            foreach (var cart in cartList)
            {
                OrderDetail orderDetail = new OrderDetail()
                {
                    OrderId = order.OrderId,
                    GameId = cart.GameId,
                    Quantity = cart.Quantity,
                    Price = cart.Game.Price

                };

                _context.Add(orderDetail);
                _context.SaveChanges();

            }

        }

        public void ClearCartSession()
        {
            //clear the session cookie and direct to login page at /Login/Index
            EmptyCart();
            HttpContext.Session.Clear();
        }

        public void EmptyCart()
        {
            string sessionId = Request.Cookies["CartSessionId"];
            var cartItems = _context.Carts.Where(cart => cart.SessionId == sessionId);

            foreach (var cartItem in cartItems)
            {
                _context.Carts.Remove(cartItem);
            }

            // Save changes
            _context.SaveChanges();
        }

        public List<OrderDetail> GetOrderDetails(string sessionId)
        {
            Order order = _context.Orders.Find(sessionId);
            List<OrderDetail> orderdetails = _context.OrderDetails.Where(x => x.OrderId == order.OrderId).ToList();

            return orderdetails;
        }

        public void GenerateActivationCode()
        {
            //get order details
            string sessionId = Request.Cookies["CartSessionId"];

            List<OrderDetail> OrderDetailList = GetOrderDetails(sessionId);

            foreach (var item in OrderDetailList)
            {
                for (int i = 0; i < item.Quantity; i++)
                {
                    ActivationCode active = new ActivationCode()
                    {
                        OrderDetailId = item.Id,
                        Activationcode = Guid.NewGuid()
                    };
                    _context.Add(active);
                }

                // Save changes
                _context.SaveChanges();
            }
        }

    }
}

    

GameStore1/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GameStore1.DB;
using GameStore1.Models;
using Microsoft.AspNetCore.Http;

namespace GameStore1.Controllers
{
	public class GamesController : Controller
	{
		private readonly GameContext _context;

		public GamesController(GameContext context)
		{
			_context = context;
		}

		// GET: Games
		public async Task<IActionResult> Index(string SearchString)
		{
			if (Request.Cookies["CartSessionId"] == null)
			{
				string sessionId = StartCartSession();
				Session session = new Session()
				{
					Id = sessionId
				};
				_context.Add(session);
				_context.SaveChanges();
			}

			var games = from m in _context.Games
				select m;
			if (!string.IsNullOrEmpty(SearchString))
			{
				games = games.Where(s => s.Title.Contains(SearchString)|| s.GenreId.Contains(SearchString));
			}


			return View(await games.ToListAsync());
		}


		public string StartCartSession()
		{
			string sessionId = System.Guid.NewGuid().ToString();
			CookieOptions options = new CookieOptions();
			Response.Cookies.Append("CartSessionId", sessionId, options);

			return sessionId;
		}


		public List<Game> GetGamesByGenre(string GenreId)
		{
				List<Game> games = _context.Games.Where(x => x.GenreId == GenreId).ToList();
				return games;	
		}

		public IActionResult Details(string id)
		{
			var game = _context.Games.Find(id);

			return View(game);
		}





	}
}

GameStore1/Controllers/ShoppingCartController.cs
using GameStore1.DB;
using GameStore1.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Collections.Generic;

namespace NetCoreCA.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly GameContext _context;

        public ShoppingCartController(GameContext context)
        {
            _context = context;
        }

        // GET: /ShoppingCart/
        public IActionResult Index()
        {
            List<Cart> viewcarts = GetCart();
            decimal gettotal = GetTotal();
            ViewData["Total"] = gettotal.ToString("0.00");
            ViewData["Count"] = GetCount();
            return View(viewcarts);
        }

        //To display cart items
        public List<Cart> GetCart()
        {
            string CartSessionId = Request.Cookies["CartSessionId"];
            List<Cart> cartitems = _context.Carts.Where(x => x.SessionId == CartSessionId).ToList();
            return cartitems;
        }


        public IActionResult AddToCart(string Id)
        {
            //Retrieve Cart
            string sessionId = Request.Cookies["CartSessionId"];
            Session session = _context.Sessions.Find(sessionId);
            Game game = _context.Games.Find(Id);

            //check if product exists in cart 
            Cart cart_check = _context.Carts.Where(x => x.GameId == Id && x.SessionId == sessionId).FirstOrDefault();

            
            //If cart does not exist
            if (cart_check == null)
            {
                Cart cart = new Cart()
                {
                    SessionId = sessionId,
                    GameId = Id,
                    Quantity = 1,
                };

                _context.Add(cart);
                _context.SaveChanges();
            }

            else
            {
                cart_check.Quantity++;
                _context.Update(cart_check);
                _context.SaveChanges();
            }

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }

        public IActionResult RemoveFromCart(string id)
        {
            string sessionId = Request.Cookies["CartSessionId"];
            var cartItem = _context.Carts.Single(cart => cart.SessionId == sessionId && cart.GameId == id);
       
            if (cartItem != null)
            { 
                _context.Carts.Remove(cartItem);
                _context.SaveChanges();

            }

            return RedirectToAction("Index");
        }

        public IActionResult AddProduct(string id)
        {
            string sessionId = Request.Cookies["CartSessionId"];
            var cartItem = _context.Carts.Single(cart => cart.SessionId == sessionId && cart.GameId == id);

            if (cartItem != null)
            {
                cartItem.Quantity++;

            }
            _context.Update(cartItem);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult ReduceProduct(string id)
        {
            string sessionId = Request.Cookies["CartSessionId"];
            var cartItem = _context.Carts.Single(cart => cart.SessionId == sessionId && cart.GameId == id);

            if (cartItem != null && cartItem.Quantity >1)
            {
                cartItem.Quantity--;

            }
            _context.Update(cartItem);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult EmptyCart()
        {
            string sessionId = Request.Cookies["CartSessionId"];
            var cartItems = _context.Carts.Where(cart => cart.SessionId == sessionId);

            foreach (var cartItem in cartItems)
            {
                _context.Carts.Remove(cartItem);
            }

            // Save changes
            _context.SaveChanges();

            return RedirectToAction("Index");
        }


        public IActionResult CartSummary()
        {
           return RedirectToAction("Index");
        }

        public int GetCount()
        {
            string sessionId = Request.Cookies["CartSessionId"];
            int? count = (from cartItems in _context.Carts
                          where cartItems.SessionId == sessionId
                          select (int?)cartItems.Quantity).Sum();

            // Return 0 if all entries are null
            return count ?? 0;
        }

        public decimal GetTotal()
        {
            string sessionId = Request.Cookies["CartSessionId"];
            decimal? total = (from cartItems in _context.Carts
                              where cartItems.SessionId == sessionId
                              select (int?)cartItems.Quantity * cartItems.Game.Price).Sum();

            //return total ?? decimal.Zero;
            return total ?? decimal.Zero;
        }

        //public IActionResult RemoveFromCart(string id)
        //{
        //    string sessionId = Request.Cookies["CartSessionId"];
        //    var cartItem = _context.Carts.Single(cart => cart.SessionId == sessionId && cart.GameId == id);

        //    if (cartItem != null)
        //    {
        //        if (cartItem.Quantity > 1)
        //        {
        //            cartItem.Quantity--;

        //        }
        //        else
        //        {
        //            _context.Carts.Remove(cartItem);
        //        }

        //        _context.Update(cartItem);
        //        _context.SaveChanges();
        //    }
        //    return RedirectToAction("Index");
        //}

    }
}

GameStore1/Views/ShoppingCart/Index.cshtml
@{
    ViewData["Title"] = "Shopping Cart";
}
@model List<GameStore1.Models.Cart>

<script type="text/javascript">
    $(function () {
        // Document.ready -> link up remove event handler
        $(".RemoveLink").click(function () {
            // Get the id from the link
            var recordToDelete = $(this).attr("data-id");
            if (recordToDelete != '') {
                // Perform the ajax post
                $.post("/ShoppingCart/RemoveFromCart", { "id": recordToDelete },
                    function (data) {
                        // Successful requests get here
                        // Update the page elements
                        if (data.ItemCount == 0) {
                            $('#row-' + data.DeleteId).fadeOut('slow');
                        } else {
                            $('#item-count-' + data.DeleteId).text(data.ItemCount);
                        }
                        $('#cart-total').text(data.CartTotal);
                        $('#update-message').text(data.Message);
                        $('#cart-status').text('Cart (' + data.CartCount + ')');
                    });
            }
        });
    });
</script>

<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-cart.css" />
</head>

<body>

    <div class="container">
        <div class="card shopping-cart">
            <div class="card-header bg-#696969 text-#DCDCDC">
                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                Shopping cart @ViewData["Count"]
                <a asp-area="" asp-controller="Games" asp-action="Index" class="btn btn-outline-info btn-sm pull-right">Continue shopping</a>
                <div class="clearfix"></div>
            </div>
            <div class="card-body">
                <!-- PRODUCT -->
                @foreach (var cartItems in Model)
                {
                    <div class="row">

                        <div class="col-12 col-sm-12 col-md-2 text-center">
                            <img class="img-responsive" src="@Html.DisplayFor(modelItem => cartItems.Game.ImageURL)" alt="@Html.DisplayFor(modelItem => cartItems.Game.Title)" width="120" height="80">
                        </div>
                        <div class="col-12 text-sm-center col-sm-12 text-md-left col-md-6">
                            <h4 class="product-name"><strong>@Html.DisplayFor(modelItem => cartItems.Game.Title)</strong></h4>
                        </div>
                        <div class="col-12 col-sm-12 text-sm-center col-md-4 text-md-right row">
                            <div class="col-3 col-sm-3 col-md-6 text-md-right" style="padding-top: 5px">
                                <h6><strong>@Html.DisplayFor(modelItem => cartItems.Game.Price)<span class="text-muted">x</span></strong></h6>
                            </div>
                            <div class="col-4 col-sm-4 col-md-4">
                                <div class="quantity">
                                    <input type="number" step="1" max="99" min="1" value="@Html.DisplayFor(modelItem => cartItems.Quantity)" title="Qty" class="qty"
                                           size="4">
                                </div>
                            </div>
                            <div class="col-2 col-sm-2 col-md-2 text-right">
                                <span class="badge badge-light">
                                    @Html.ActionLink("Add", "AddProduct",
                                        "ShoppingCart", new { id = cartItems.GameId })
                                </span>
                                <br />
                                <span class="badge badge-light">
                                    @Html.ActionLink("Reduce", "ReduceProduct",
                                        "ShoppingCart", new { id = cartItems.GameId })
                                </span>
                                <br />
                                <span class="badge badge-light">
                                    @Html.ActionLink("Remove", "RemoveFromCart",
                                        "ShoppingCart", new { id = cartItems.GameId })
                                </span>
                            </div>
                        </div>
                    </div>
                    <hr>

                }
                <!-- END PRODUCT -->

                <div class="pull-right" style="margin: 5px">
                    Total price: <b>$@ViewData["Total"]</b>
                </div>
            </div>
            <div class="card-footer">
                <div class="col-6">
                    <p>
                        @Html.ActionLink("Empty Cart", "EmptyCart",
                            "ShoppingCart")
                    </p>
                </div>
            </div>
        </div>
        <div class="pull-right" style="margin: 10px">
            <button type="button" class="btn btn-success" onclick="@("window.location.href='" + @Url.Action("Index", "Checkout") + "'");">
                Checkout <span class="glyphicon glyphicon-play"></span>
            </button>
        </div>
    </div>
    </div>
    </div>

    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="https://use.fontawesome.com/c560c025cf.js"></script>

</body>
</html>