GameStore1/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GameStore1.DB;
using GameStore1.Models;
using Microsoft.AspNetCore.Http;

namespace GameStore1.Controllers
{
	public class GamesController : Controller
	{
		private readonly GameContext _context;

		public GamesController(GameContext context)
		{
			_context = context;
		}

		// GET: Games
		public async Task<IActionResult> Index(string SearchString)
		{
			if (Request.Cookies["CartSessionId"] == null)
			{
				string sessionId = StartCartSession();
				Session session = new Session()
				{
					Id = sessionId
				};
				_context.Add(session);
				_context.SaveChanges();
			}

			var games = from m in _context.Games
				select m;
			if (!string.IsNullOrEmpty(SearchString))
			{
				games = games.Where(s => s.Title.Contains(SearchString)|| s.GenreId.Contains(SearchString));
			}


			return View(await games.ToListAsync());
		}


		public string StartCartSession()
		{
			string sessionId = System.Guid.NewGuid().ToString();
			CookieOptions options = new CookieOptions();
			Response.Cookies.Append("CartSessionId", sessionId, options);

			return sessionId;
		}


		public List<Game> GetGamesByGenre(string GenreId)
		{
				List<Game> games = _context.Games.Where(x => x.GenreId == GenreId).ToList();
				return games;	
		}

		public IActionResult Details(string id)
		{
			var game = _context.Games.Find(id);

			return View(game);
		}





	}
}

GameStore1/Controllers/MyPurchasesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GameStore1.DB;
using GameStore1.Models;
using Microsoft.AspNetCore.Mvc;

namespace NetCoreCA.Controllers
{
    public class MyPurchasesController : Controller
    {
        private readonly GameContext _context;

        public MyPurchasesController(GameContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            string sessionId = Request.Cookies["CartSessionId"];

           //get order 
            Order order = GetOrder(sessionId);

            //get OrderDetailList
            List<OrderDetail> orderdetails = _context.OrderDetails.Where(x => x.OrderId == order.OrderId).ToList();


            return View(orderdetails);
        }

        public IActionResult GetActivationCode(OrderDetail orderdetail)
        {
            List<ActivationCode> activeList = _context.ActivationCodes.Where(x => x.OrderDetailId ==orderdetail.Id).ToList();

            return RedirectToAction("Index");
        }

        public Order GetOrder(string sessionId)
        {
            Order order = _context.Orders.Find(sessionId);
            return order;
        }



    }  
}

GameStore1/Controllers/ShoppingCartController.cs
using GameStore1.DB;
using GameStore1.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Collections.Generic;

namespace NetCoreCA.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly GameContext _context;

        public ShoppingCartController(GameContext context)
        {
            _context = context;
        }

        // GET: /ShoppingCart/
        public IActionResult Index()
        {
            List<Cart> viewcarts = GetCart();
            decimal gettotal = GetTotal();
            ViewData["Total"] = gettotal.ToString("0.00");
            ViewData["Count"] = GetCount();
            return View(viewcarts);
        }

        //To display cart items
        public List<Cart> GetCart()
        {
            string CartSessionId = Request.Cookies["CartSessionId"];
            List<Cart> cartitems = _context.Carts.Where(x => x.SessionId == CartSessionId).ToList();
            return cartitems;
        }


        public IActionResult AddToCart(string Id)
        {
            //Retrieve Cart
            string sessionId = Request.Cookies["CartSessionId"];
            Session session = _context.Sessions.Find(sessionId);
            Game game = _context.Games.Find(Id);

            //check if product exists in cart 
            Cart cart_check = _context.Carts.Where(x => x.GameId == Id && x.SessionId == sessionId).FirstOrDefault();

            
            //If cart does not exist
            if (cart_check == null)
            {
                Cart cart = new Cart()
                {
                    SessionId = sessionId,
                    GameId = Id,
                    Quantity = 1,
                };

                _context.Add(cart);
                _context.SaveChanges();
            }

            else
            {
                cart_check.Quantity++;
                _context.Update(cart_check);
                _context.SaveChanges();
            }

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }

        public IActionResult RemoveFromCart(string id)
        {
            string sessionId = Request.Cookies["CartSessionId"];
            var cartItem = _context.Carts.Single(cart => cart.SessionId == sessionId && cart.GameId == id);
       
            if (cartItem != null)
            { 
                _context.Carts.Remove(cartItem);
                _context.SaveChanges();

            }

            return RedirectToAction("Index");
        }

        public IActionResult AddProduct(string id)
        {
            string sessionId = Request.Cookies["CartSessionId"];
            var cartItem = _context.Carts.Single(cart => cart.SessionId == sessionId && cart.GameId == id);

            if (cartItem != null)
            {
                cartItem.Quantity++;

            }
            _context.Update(cartItem);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult ReduceProduct(string id)
        {
            string sessionId = Request.Cookies["CartSessionId"];
            var cartItem = _context.Carts.Single(cart => cart.SessionId == sessionId && cart.GameId == id);

            if (cartItem != null && cartItem.Quantity >1)
            {
                cartItem.Quantity--;

            }
            _context.Update(cartItem);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        public IActionResult EmptyCart()
        {
            string sessionId = Request.Cookies["CartSessionId"];
            var cartItems = _context.Carts.Where(cart => cart.SessionId == sessionId);

            foreach (var cartItem in cartItems)
            {
                _context.Carts.Remove(cartItem);
            }

            // Save changes
            _context.SaveChanges();

            return RedirectToAction("Index");
        }


        public IActionResult CartSummary()
        {
           return RedirectToAction("Index");
        }

        public int GetCount()
        {
            string sessionId = Request.Cookies["CartSessionId"];
            int? count = (from cartItems in _context.Carts
                          where cartItems.SessionId == sessionId
                          select (int?)cartItems.Quantity).Sum();

            // Return 0 if all entries are null
            return count ?? 0;
        }

        public decimal GetTotal()
        {
            string sessionId = Request.Cookies["CartSessionId"];
            decimal? total = (from cartItems in _context.Carts
                              where cartItems.SessionId == sessionId
                              select (int?)cartItems.Quantity * cartItems.Game.Price).Sum();

            //return total ?? decimal.Zero;
            return total ?? decimal.Zero;
        }

        //public IActionResult RemoveFromCart(string id)
        //{
        //    string sessionId = Request.Cookies["CartSessionId"];
        //    var cartItem = _context.Carts.Single(cart => cart.SessionId == sessionId && cart.GameId == id);

        //    if (cartItem != null)
        //    {
        //        if (cartItem.Quantity > 1)
        //        {
        //            cartItem.Quantity--;

        //        }
        //        else
        //        {
        //            _context.Carts.Remove(cartItem);
        //        }

        //        _context.Update(cartItem);
        //        _context.SaveChanges();
        //    }
        //    return RedirectToAction("Index");
        //}

    }
}

GameStore1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GameStore1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-main.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="navbar-header pull-left">
                <a class="navbar-brand" asp-area="" asp-controller="Login" asp-action="Index"><img width=70 px src="/Logo_Images/StoreLogo.png" title="Home Page" alt="Logo" /></a>
            </div>

            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav mr-auto">

                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Games" asp-action="Index">Store</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Login" asp-action="Privacy">Privacy</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Log In/Out</a>
                        <div class="dropdown-menu" style="">
                            <a class="dropdown-item" asp-area="" asp-controller="Login" asp-action="Index">Log In</a>
                            <a class="dropdown-item" href="@Url.Action("LogOut", "Login")">Log Out</a>
                        </div>
                    </li>
                </ul>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <form class="form-inline my-2 my-lg-0">
                        <button asp-area="" asp-controller="MyPurchases" asp-action="Index" class="btn btn-primary disabled my-2 my-sm-0" style="font-size: 27px"><i class="fa fa-history" aria-hidden="true" title="My Purchases"></i></button>
                        <button asp-area="" asp-controller="ShoppingCart" asp-action="Index" class="btn btn-primary disabled my-2 my-sm-0" style="font-size: 27px"><i class="fa fa-shopping-cart" title="Shopping Cart"></i></button>
                        <p class="text-muted">@ViewData["Count"]</p>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - GameStore1 - <a asp-area="" asp-controller="Login" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>